version: "3.1"
services:
  web:
      image: redcarrottt/hawkeye:arm64
      build: .
      ports:
        - "3000-3001:3000-3001"
      volumes:
        - hawkeye-workspace:/home/hawkeye/hawkeye/workspace
      command: bash -c "cd /home/hawkeye/hawkeye/ && git fetch && git checkout -f origin/master && cd web && npm install && cd .. && python3 ./hawkeye.py"
volumes:
    hawkeye-workspace:
