version: "3.1"
services:
  web:
      image: redcarrottt/hawkeye:x86_64
      build: .
      ports:
        - "3000-3001:3000-3001"
      volumes:
        - hawkeye-workspace:/home/hawkeye/hawkeye/workspace
      command: bash -c "cd /home/hawkeye/hawkeye/ && git pull origin master && python3 ./hawkeye.py"
volumes:
    hawkeye-workspace:
